name: Generate Snake

on:
  schedule:
    # Run every day at 11:59 PM (UTC) "minute 59, hour 23, day of month *, month *, day of week *"
    - cron: "59 23 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: oscarnar
          svg_out_path: dist/assets/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: master
          build_dir: dist
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
